version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-web
    ports:
      - "8080:80"
    volumes:
      - C:/Users/tooch/Downloads/security/admin:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: mysql-db2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: ezzy_nursing
      MYSQL_PASSWORD: root
    ports:
      - "50888:3306"
  adminer:
    image: adminer
    container_name: adminer-container
    ports:
      - "8081:8080"



